# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         OOB
version:      0.11
version_from: lib/OOB.pm
installdirs:  site
requires:
    Scalar::Util:                  1.14
    Sub::Identify:                 0.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
