---
abstract: 'out of band data for any data structure in Perl'
author:
  - 'Elizabeth Mattijsen (liz@dijkmat.nl)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: OOB
no_index:
  directory:
    - t
    - inc
requires:
  Scalar::Util: 1.14
  Sub::Identify: 0.02
version: 0.12
